//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laba.Eng", typeof(Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string string1 {
            get {
                return ResourceManager.GetString("string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string string2 {
            get {
                return ResourceManager.GetString("string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string string3 {
            get {
                return ResourceManager.GetString("string3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art and Design :.
        /// </summary>
        internal static string t_ArtAndDesign {
            get {
                return ResourceManager.GetString("t_ArtAndDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string t_detail_country {
            get {
                return ResourceManager.GetString("t_detail_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string t_detail_description {
            get {
                return ResourceManager.GetString("t_detail_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre :.
        /// </summary>
        internal static string t_detail_genre {
            get {
                return ResourceManager.GetString("t_detail_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main roles :.
        /// </summary>
        internal static string t_detail_mainroles {
            get {
                return ResourceManager.GetString("t_detail_mainroles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motto :.
        /// </summary>
        internal static string t_detail_motto {
            get {
                return ResourceManager.GetString("t_detail_motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer :.
        /// </summary>
        internal static string t_detail_producer {
            get {
                return ResourceManager.GetString("t_detail_producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year :.
        /// </summary>
        internal static string t_detail_year {
            get {
                return ResourceManager.GetString("t_detail_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive producer :.
        /// </summary>
        internal static string t_EProg {
            get {
                return ResourceManager.GetString("t_EProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string t_favorites {
            get {
                return ResourceManager.GetString("t_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        internal static string t_films_title {
            get {
                return ResourceManager.GetString("t_films_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a search word.
        /// </summary>
        internal static string t_input {
            get {
                return ResourceManager.GetString("t_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string t_options_title {
            get {
                return ResourceManager.GetString("t_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string t_picker_title {
            get {
                return ResourceManager.GetString("t_picker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgEngineer :.
        /// </summary>
        internal static string t_ProgE {
            get {
                return ResourceManager.GetString("t_ProgE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager :.
        /// </summary>
        internal static string t_ProjM {
            get {
                return ResourceManager.GetString("t_ProjM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string t_search_title {
            get {
                return ResourceManager.GetString("t_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string t_tab_switch1 {
            get {
                return ResourceManager.GetString("t_tab_switch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        internal static string t_tab_switch2 {
            get {
                return ResourceManager.GetString("t_tab_switch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string t_tab_switch3 {
            get {
                return ResourceManager.GetString("t_tab_switch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings :.
        /// </summary>
        internal static string t_tab_title1 {
            get {
                return ResourceManager.GetString("t_tab_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme settings :.
        /// </summary>
        internal static string t_tab_title2 {
            get {
                return ResourceManager.GetString("t_tab_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About programmer :.
        /// </summary>
        internal static string t_tab_title3 {
            get {
                return ResourceManager.GetString("t_tab_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string t_view_back {
            get {
                return ResourceManager.GetString("t_view_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string t_view_delete {
            get {
                return ResourceManager.GetString("t_view_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Favorites.
        /// </summary>
        internal static string t_view_fav {
            get {
                return ResourceManager.GetString("t_view_fav", resourceCulture);
            }
        }
    }
}
